version: "3"
services:
  caddy:
    image: "abiosoft/caddy:latest"
    volumes:
      - ./caddy:/root/.caddy
      - ./Caddyfile:/etc/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  app:
    build: .
    depends_on:
      - redis
    environment:
      REDIS_ADDR: redis:6379
    env_file:
      - .env

  redis:
    image: bitnami/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - /var/redis-persistence:/bitnami/redis/data
